apiVersion: v2
name: front
description: Frontend - Next.js app calling backend-1 and backend-2
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: app
    version: 0.3.0
    repository: oci://ghcr.io/amine7536/akpe-charts
    alias: app
