replicaCount: 1

image:
  repository: ghcr.io/amine7536/akpe-front
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 3000

ingress:
  enabled: true
  host: front.127.0.0.1.nip.io

env:
  BACKEND_1_URL: "http://backend-1:8080"
  BACKEND_2_URL: "http://backend-2:8080"
