name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: amine7536/akpe-workflows/.github/workflows/build-and-push.yml@main
    with:
      image_name: ${{ github.repository }}
    secrets: inherit

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build-and-push
    uses: amine7536/akpe-workflows/.github/workflows/deploy-preview.yml@main
    with:
      service_name: front
    secrets: inherit
